#!/bin/bash
tput clear
tput cup 0 0
echo "******************************************************************************"
tput cup 1 0
echo "******************************************************************************"
tput cup 20 0
echo "******************************************************************************"
tput cup 21 0
echo "******************************************************************************"
tput cup 6 33
echo "PROJECT"
tput cup 9 35
echo "ON"
tput cup 12 26
echo "JEWELLERY DELIVERY REPORT"
tput cup 19 50
echo "press any key to continue..."
read x
